spring:
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: root
    password: 123qwe
    driver-class-name: org.postgresql.Driver

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true