spring:
  application:
    name: ai
  docker:
    compose:
      enabled: false
  ai:
    chat:
      client:
        enabled: true
    openai:
      chat:
        options:
          model: gpt-5-mini
          temperature: 1.0
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG